# Used to broadcast the current mode to tell which nodes to activate
# Used to broadcast the current mode to tell which nodes to activate

#Gives the modes and mode contains the integer value
int8 TAKEOFF=0
int8 FOLLOW=1
int8 LEAVE=2
int8 RETURN=3
int8 LAND=4
int8 LANDED=5
int8 HOVER=6

int8 mode
---
bool success
